export const GET_ALL_AGENCYS_REQUEST = 'GET_ALL_AGENCYS_REQUEST';
export const GET_ALL_AGENCYS_SUCCESS = 'GET_ALL_AGENCYS_SUCCESS';
export const GET_ALL_AGENCYS_FAIL = 'GET_ALL_AGENCYS_FAIL';
export const GET_ALL_AGENCYS_RESET = 'GET_ALL_AGENCYS_RESET';

export const ADD_AGENCY_REQUEST = 'ADD_AGENCY_REQUEST';
export const ADD_AGENCY_SUCCESS = 'ADD_AGENCY_SUCCESS';
export const ADD_AGENCY_FAIL = 'ADD_AGENCY_FAIL';
export const ADD_AGENCY_RESET = 'ADD_AGENCY_RESET';

export const UPDATE_AGENCY_REQUEST = 'UPDATE_AGENCY_REQUEST';
export const UPDATE_AGENCY_SUCCESS = 'UPDATE_AGENCY_SUCCESS';
export const UPDATE_AGENCY_FAIL = 'UPDATE_AGENCY_FAIL';
export const UPDATE_AGENCY_RESET = 'UPDATE_AGENCY_RESET';

export const DELETE_AGENCY_REQUEST = 'DELETE_AGENCY_REQUEST';
export const DELETE_AGENCY_SUCCESS = 'DELETE_AGENCY_SUCCESS';
export const DELETE_AGENCY_FAIL = 'DELETE_AGENCY_FAIL';
export const DELETE_AGENCY_RESET = 'DELETE_AGENCY_RESET';

export const GET_AGENCY_REQUEST = 'GET_AGENCY_REQUEST';
export const GET_AGENCY_SUCCESS = 'GET_AGENCY_SUCCESS';
export const GET_AGENCY_FAIL = 'GET_AGENCY_FAIL';
export const GET_AGENCY_RESET = 'GET_AGENCY_RESET';
