export const GET_ALL_RESELLERS_REQUEST = 'GET_ALL_RESELLERS_REQUEST';
export const GET_ALL_RESELLERS_SUCCESS = 'GET_ALL_RESELLERS_SUCCESS';
export const GET_ALL_RESELLERS_FAIL = 'GET_ALL_RESELLERS_FAIL';
export const GET_ALL_RESELLERS_RESET = 'GET_ALL_RESELLERS_RESET';
