export const GET_ALL_ROOMS_REQUEST = 'GET_ALL_ROOMS_REQUEST';
export const GET_ALL_ROOMS_SUCCESS = 'GET_ALL_ROOMS_SUCCESS';
export const GET_ALL_ROOMS_FAIL = 'GET_ALL_ROOMS_FAIL';
export const GET_ALL_ROOMS_RESET = 'GET_ALL_ROOMS_RESET';

export const ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';
export const ADD_ROOM_RESET = 'ADD_ROOM_RESET';

export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL';
export const UPDATE_ROOM_RESET = 'UPDATE_ROOM_RESET';

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';
export const DELETE_ROOM_RESET = 'DELETE_ROOM_RESET';

export const GET_ROOM_REQUEST = 'GET_ROOM_REQUEST';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAIL = 'GET_ROOM_FAIL';
export const GET_ROOM_RESET = 'GET_ROOM_RESET';
