export const GET_ALL_STORES_REQUEST = 'GET_ALL_STORES_REQUEST';
export const GET_ALL_STORES_SUCCESS = 'GET_ALL_STORES_SUCCESS';
export const GET_ALL_STORES_FAIL = 'GET_ALL_STORES_FAIL';
export const GET_ALL_STORES_RESET = 'GET_ALL_STORES_RESET';
